# Nethical Satellite Region Overlay
# Optimized for satellite connectivity with higher timeouts and retry policies
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nethical-satellite
  annotations:
    nethical.io/connectivity-type: "satellite"
    nethical.io/latency-profile: "high"

namespace: nethical

resources:
  - ../../base
  - virtual-service.yaml
  - destination-rule.yaml
  - network-policy.yaml

commonLabels:
  region: satellite
  region-role: edge
  connectivity-type: satellite
  topology.kubernetes.io/region: satellite

commonAnnotations:
  nethical.io/connectivity-type: "satellite"
  nethical.io/latency-profile: "high"
  nethical.io/failover-enabled: "true"

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NETHICAL_SATELLITE_MODE
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NETHICAL_LATENCY_TOLERANCE_MS
          value: "500"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NETHICAL_CACHE_TTL_MULTIPLIER
          value: "3"
    target:
      kind: Deployment
      name: nethical-api

configMapGenerator:
  - name: nethical-config
    behavior: merge
    literals:
      - NETHICAL_REGION_ID=satellite
      - REGION=satellite
      - REGION_ROLE=edge
      - DATABASE_READ_WRITE=false
      - NETHICAL_CONNECTIVITY_TYPE=satellite
      - NETHICAL_LATENCY_PROFILE=high
      - NETHICAL_FAILOVER_ENABLED=true
      - NETHICAL_OFFLINE_CACHE_ENABLED=true
      - NETHICAL_COMPRESSION_ENABLED=true
      - NETHICAL_BATCH_REQUESTS_ENABLED=true
      - SYNC_PEERS=nethical-api.us-east-1.nethical.io,nethical-api.eu-west-1.nethical.io
