apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nethical-us-east-1

namespace: nethical

resources:
  - ../../base

commonLabels:
  region: us-east-1
  region-role: primary

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "2Gi"
    target:
      kind: Deployment
      name: nethical-api

configMapGenerator:
  - name: nethical-config
    behavior: merge
    literals:
      - REGION=us-east-1
      - REGION_ROLE=primary
      - DATABASE_READ_WRITE=true
      - SYNC_PEERS=nethical-api.eu-west-1.nethical.io,nethical-api.ap-south-1.nethical.io
