apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nethical-api
  namespace: nethical
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nethical
      app.kubernetes.io/component: api
