---
# EKS ServiceAccount Patch
# Configures IRSA for AWS IAM integration
#
# IMPORTANT: Before deploying, replace YOUR_ACCOUNT_ID with your actual AWS account ID
# Example: arn:aws:iam::123456789012:role/nethical-eks-role
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nethical
  namespace: nethical
  annotations:
    # IRSA annotation
    # TODO: Replace YOUR_ACCOUNT_ID with your AWS account ID before deployment
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/nethical-eks-role
