apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nethical-base

# Reference the main kubernetes manifests
resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../secret.yaml
  - ../../serviceaccount.yaml
  - ../../pvc.yaml
  - ../../statefulset.yaml
  - ../../service.yaml
  - ../../hpa.yaml
  - ../../pdb.yaml
  - ../../network-policies.yaml

commonLabels:
  app.kubernetes.io/name: nethical
  app.kubernetes.io/part-of: nethical-governance
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  nethical.io/version: "0.1.0"
